# grafana/Dockerfile
FROM grafana/grafana:latest

# Variables de entorno (puedes sobreescribirlas en Railway)
ENV GF_SECURITY_ADMIN_USER=admin
ENV GF_SECURITY_ADMIN_PASSWORD=adminadmin123

# Puerto por defecto de Grafana
EXPOSE 3000
